version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.24.2
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.0
